version: '3.8'

services: 
  mongo-db:
    image: mongo:6.0.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mussiagus
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/date/db
    ports:
      - 27017:27017